services:
    laravel.prod:
        env_file:
            - .env.prod
        build:
            context: ./
            dockerfile: Dockerfile
        image: ghcr.io/olekluk/v:latest
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - prod
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'prod-mysql:/var/lib/mysql'
        networks:
            - prod
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'prod-redis:/data'
        networks:
            - prod
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    prod:
        driver: bridge
volumes:
    prod-mysql:
        driver: local
    prod-redis:
        driver: local
